apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8gsh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8gsh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8gsh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8gsh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8gsh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltrl-tenant/rhtap-demo-app/hacbs-test-project-8gsh@sha256:aaf9731e798b188191d9a8d722ea9e58d9bcc460c98085f993d80db51d2cd25e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
