apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-8gsh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltrl-tenant/rhtap-demo-app/hacbs-test-project-8gsh@sha256:aaf9731e798b188191d9a8d722ea9e58d9bcc460c98085f993d80db51d2cd25e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
