apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-8gsh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltrl-tenant/rhtap-demo-app/hacbs-test-project-8gsh@sha256:9a2a407d01e939a8ad9df03ec856ecae3e6f55b169078b99fe99336a3e75207a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
